### ISSUE TITLE
Recording with background music doesn't work when headset is connected

### ISSUE THREAD

**Issue by coolhunter33** [NateRickard/Plugin.AudioRecorder#10]
Hi.

I am currently using your plugin in the scenario when I am running a MediaPlayer with some background music and also starting the voice recording with the help of your code.

But if I connect a headset and try to do the same - I receive only the recorded voice and no music.

Do you know how to correct that?

Thanks in advance.

**Comment by NateRickard** [comment]
I'm not really sure without investigating further, but you'd probably need to adjust the way it's configuring/using the underlying audio APIs (e.g. InputAudioQueue on iOS) to record more than just mic input.  This lib was really just for recording mic input, so I didn't dig into that extensively.
