### ISSUE TITLE
This plugin does not work

### ISSUE THREAD

**Issue by OneMiay** [NateRickard/Plugin.AudioRecorder#18]
I spent one week and did not manage to launch this plugin.
It is compiled and deployed onto the device, but it does not work. In debag mode, it returns the name of the file, but it does not exist on the device. All permissions are set correctly.

Xiaomi Redmi 5 Plus Android 7.1.

**Comment by KithorasCarzyl** [comment]
@OneMiay Have you tried copying it to another place? I had the same problem, but after copying it to my music folder it appeared.

**Comment by NateRickard** [comment]
That's interesting re: the file copying.  I've not had to do that, but maybe some devices behave differently.
