### ISSUE TITLE
Question: create the spectogram related to audio record

### ISSUE THREAD

**Issue by Goldstrike** [NateRickard/Plugin.AudioRecorder#19]
Hello,

I would like to know if you see a way to create a spectogram related to the audio record?

Regards,

**Comment by NateRickard** [comment]
I've not looked into this at all as it's not core to the goal of the library. If you find a way to do it and think it would be useful in this plugin, feel free to send a PR.

**Comment by Goldstrike** [comment]
Thanks @NateRickard 
I will do it through a dedicated charts library: SciChart.
However, can we use your plugin to make a custom treatment during the audio recording?
In my case I need to send bytes to the chart datas, and in the same time write the file.

**Comment by NateRickard** [comment]
https://github.com/NateRickard/Plugin.AudioRecorder#concurrent-streaming

You can get a Stream to the audio as it's recording and maybe feed that into the chart that way.  I use this in https://github.com/NateRickard/Xamarin.Cognitive.BingSpeech to stream the audio data while it's still being recorded.
