### ISSUE TITLE
Record in compressed format

### ISSUE THREAD

**Issue by encorro** [NateRickard/Plugin.AudioRecorder#24]
Hi, I am trying to modify the code to record directly in AAC format. I’ve tried to change parameters at AudioStreamBasicDescrption for iOS but no success. 

I think this would be possible, do you?. Any advice to continue or is there a possibility to enhance the code?

Thanks a lot.

**Comment by NateRickard** [comment]
Sorry I've not looked into supporting any other formats, though I do think it should be possible.  If you're able to get it working please send a PR!

**Comment by encorro** [comment]
Thanks anyway. I will continue looking for a solution. If I get it I will inform you.
