### ISSUE TITLE
Getting error "The method or operation is not implemented" while making an object

### ISSUE THREAD

**Issue by furqanali1992** [NateRickard/Plugin.AudioRecorder#25]
@NateRickard 
I copied the code from your sample project and when I run it, it gives me an exception "The method or operation is not implemented" on

       **recorder = new AudioRecorderService
                {
                    StopRecordingAfterTimeout = true,
                    TotalAudioTimeout = TimeSpan.FromSeconds(15),
                    AudioSilenceTimeout = TimeSpan.FromSeconds(2)
                };**

I have installed your latest version **V1.0.1**. I am using it in Xamarin Forms and I have given all the required permissions in Android Manifest.

**Comment by NateRickard** [comment]
A few things could cause this.  Verify the following things:

1) Make sure you've added the package to the Android project
2) Your Android project must target Android SDK 8.1, as the package no longer includes a DLL for Android 7.1

**Comment by NateRickard** [comment]
Assuming this has been resolved and closing.
