### ISSUE TITLE
Build failed with this error message about 'NuGet.Build.Packaging.0.2.5-dev.1'

### ISSUE THREAD

**Issue by ergodaveh** [NateRickard/Plugin.AudioRecorder#28]
Recent downloading of the github code and attempting to build with VS2017 15.8.2 has failed with this error message 'NuGet.Build.Packaging.0.2.5-dev.1' is not found on source.  
I have excluded<removed> the unavailable Plugin.AudioRecorder.NuGet project and tried to find the update / remove without success.

Any suggestion are appreciated

Cheers

**Comment by NateRickard** [comment]
Refer to the [Building](https://github.com/NateRickard/Plugin.AudioRecorder#building) section in the docs... you need to install the NuGet.Build.Packaging package from its custom source.  Alternatively, just exclude the NuGet project and remove all NuGet.Build.Packaging references and you can build everything else sans the NuGet package.

**Comment by ergodaveh** [comment]
Thanks for the reply.  I had attempted to remove the Nuget Packages by deleting them from the solution file.  But the only effective method was to edit each project file directly/manually.
All good.
Cheers,
