### ISSUE TITLE
Build fails due to missing resources

### ISSUE THREAD

**Issue by christiand** [NateRickard/Plugin.AudioRecorder#29]
Just trying to tinker with your app, as both an example to see how to bootstrap an app with Xamarin Forms on both android and iOS with a shared library, as well as a base for a recording app i want to make.

OSX 10.13.5
Visual Studio Community 2017
Cloned repo, opened solution file in root directory.

Package errors:
```
Restoring NuGet package NuGet.Build.Packaging.0.2.5-dev.1.
  GET https://api.nuget.org/v3-flatcontainer/nuget.build.packaging/0.2.5-dev.1/nuget.build.packaging.0.2.5-dev.1.nupkg
  NotFound https://api.nuget.org/v3-flatcontainer/nuget.build.packaging/0.2.5-dev.1/nuget.build.packaging.0.2.5-dev.1.nupkg 2494ms
Unable to find version '0.2.5-dev.1' of package 'NuGet.Build.Packaging'.
  https://api.nuget.org/v3/index.json: Package 'NuGet.Build.Packaging.0.2.5-dev.1' is not found on source 'https://api.nuget.org/v3/index.json'.

Package restore failed for project Plugin.AudioRecorder.iOS: Unable to find version '0.2.5-dev.1' of package 'NuGet.Build.Packaging'.
  https://api.nuget.org/v3/index.json: Package 'NuGet.Build.Packaging.0.2.5-dev.1' is not found on source 'https://api.nuget.org/v3/index.json'.

Package restore failed for project Plugin.AudioRecorder.Android: Unable to find version '0.2.5-dev.1' of package 'NuGet.Build.Packaging'.
  https://api.nuget.org/v3/index.json: Package 'NuGet.Build.Packaging.0.2.5-dev.1' is not found on source 'https://api.nuget.org/v3/index.json'.

Package restore failed.
```

When I try to build AudioRecord.Forms.Android, there's lots of missing resource errors 
`/Users/cd/src/rekt/Samples/Forms/AudioRecord.Forms.Android/Resources/values/styles.xml(0,0): Error APT0000: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'. (APT0000) (AudioRecord.Forms.Android)`

Was able to build and run ..Forms.iOS in simulator!

**Comment by NateRickard** [comment]
The `NuGet.Build.Packaging` package takes some setup as it comes from a non-standard NuGet server.  You can set it up (per the readme) or remove it to get everything building.  See #28 

Re: the resource errors, you may need to update your Android SDK bits and build tools.  Those errors tend to pop up when a project targets a version of Android + support library but it can't find the needed resources locally on your machine.
