### ISSUE TITLE
Set the filepath

### ISSUE THREAD

**Issue by tonylekhtman** [NateRickard/Plugin.AudioRecorder#3]
It would be really helpful if there will be an option to change the filepath from the default one.

**Comment by NateRickard** [comment]
Great idea - I've never had the need to record multiple files or later the path but I can see some use cases where you might want that.  This should be fairly trivial to implement - feel free to submit a pull request.  Otherwise I'll look at doing this the next time I have this project open.

**Comment by NateRickard** [comment]
@ryanwersal made this possible in #15
