### ISSUE TITLE
Doesn't work on Asus Zenfone Max M1

### ISSUE THREAD

**Issue by jerryno6** [NateRickard/Plugin.AudioRecorder#31]
It can record audio, but when we play the recorded audio , nothing has happened, no voice, no audio from the speaker.

But if we record audio following this tutorial, it can record & play the audio on Asus Zenfone Max M1
https://github.com/xamarin/recipes/tree/master/Recipes/android/media/audio/record_audio.

29-Nov-2018: 
I found out that If we use MediaRecorder to record audio, it worked well

**Comment by NateRickard** [comment]
This is usually due to a permission or configuration issue, I would need more details to troubleshoot it.  Previous versions of this lib used `MediaRecorder` but it's now using the lower level `AudioRecord` for Android.  Should be valid for any device afaik.
