### ISSUE TITLE
Not recording on the Android Oreo but working on old version

### ISSUE THREAD

**Issue by Pritam3004** [NateRickard/Plugin.AudioRecorder#36]
Hi 
I am using Plugin.AudioRecorder in Xamarin Forms solution, target version Android 8.1(API Level -27), I have implemented as you have shown in the sample. The record functionality is working on phone with Android 6.0 but not on the latest Android version. Can you please help me with this one.

[RecordAudioPage.xaml.txt](https://github.com/NateRickard/Plugin.AudioRecorder/files/3093882/RecordAudioPage.xaml.txt)

**Comment by NateRickard** [comment]
I just tried the latest on a Pixel 2 XL running Android 9.0 and it worked ok. Can you provide any more info on the issues you're experiencing? Make sure you've reviewed and implemented the permission 'stuff': https://github.com/NateRickard/Plugin.AudioRecorder#android
