### ISSUE TITLE
Can't play the recorded audio

### ISSUE THREAD

**Issue by DD2XAlpha** [NateRickard/Plugin.AudioRecorder#37]
Hello, well as I explain in the title, I can not play the recorded audio, I checked the actual path of filePath in my device (physical) and nothing is in there.

I followed one of your <a href="https://github.com/NateRickard/Plugin.AudioRecorder/blob/master/Samples/Forms/AudioRecord.Forms/MainPage.xaml.cs">samples</a>.

- isRecording event is triggered.
- AudioInputReceived is triggered.
- filePath is different than null.
- player.play(filePath) executes with no error but the record isn't played.
- player.FinishedPlaying is not triggered.

Sorry that I can not provide my code because I can't share it.

Thanks

**Comment by Sketchizer** [comment]
I have the exact same problem.

**Comment by NateRickard** [comment]
Can you confirm that you've set the [necessary permissions](https://github.com/NateRickard/Plugin.AudioRecorder#required-permissions--capabilities)? Does the library log anything when you debug your app?

**Comment by DD2XAlpha** [comment]
I have the permissons, the phone asked for it and gave them. It doesn't throw any error at all, it just records but never saves it in the temporal folder.

I have the permissons of Data Management (because I take pictures with it) and the permisson of recording audio.

**Comment by Sketchizer** [comment]
After a bit of research in the code, I found that the "FilePath" argument can be used in the recorder initialization to specify any intended path for saving the recording. For me, I changed it to point to the local application resource folder in Xamarin.Forms & I can now view the recording in the actual folder specified.

**Comment by DD2XAlpha** [comment]
I tried to save it in a local folder but it tells me that I don't have the permissons to do so... How did you get it to work? Could you post if possible your code?

**Comment by Sketchizer** [comment]
In the platform permissions you need to request access for external storage. In Android, it is WRITE_EXTERNAL_STORAGE for example. You need to make sure that the app permissions on your phone settings shows that storage permission is enabled.

**Comment by NateRickard** [comment]
@DD2XAlpha were you able to get it working with the external storage permission?
