### ISSUE TITLE
Playing of recorded audio wav file is not working in android phones

### ISSUE THREAD

**Issue by Gr-a111y** [NateRickard/Plugin.AudioRecorder#41]
I am using the plugin as Nuget package in a xamarin forms project. I am facing issue with playing the recorded audio file in android devices only(specifically on OnePlus and Redmi phones). It works fine in iOS. 

I see that .wav file is not present in the Android file managers cache folder. Please help me with resolving the issue.

**Comment by npostma** [comment]
Also have this issue. Cant play a directly recorded issue in android. I has somthing to do with Rights or multiple Threads/Task accessing the same file. I moved over to the Plugin.MediaManager to play the audio. That works so the recorded file is fine.

**Comment by Gr-a111y** [comment]
> Also have this issue. Cant play a directly recorded issue in android. I has something to do with Rights or multiple Threads/Task accessing the same file. I moved over to the Plugin.MediaManager to play the audio. That works so the recorded file is fine.

This works for me. I am now using Plugin.Mediamanager to play audio. Thank you.

**Comment by olorunfemidavis** [comment]
I had to use the Plugin.MediaManager too in order to make it work.
