### ISSUE TITLE
 Stream is closed in WriteWavHeader

### ISSUE THREAD

**Issue by kenteman** [NateRickard/Plugin.AudioRecorder#47]
I want to use MemoryStream with "WriteWavHeader".
but Stream is closed inside "WriteWavHeader".

`using (var writer = new BinaryWriter (stream, Encoding.UTF8))`

**Comment by NateRickard** [comment]
@kenteman that wraps an [`internal` method](https://github.com/NateRickard/Plugin.AudioRecorder/blob/01e3b765a3f43cd542051de02ffcfcb24dec9c3a/Plugin.AudioRecorder.Shared/AudioFunctions.cs#L33). I can expose this as a public method if it will be useful to you.
