### ISSUE TITLE
saving mp3 or aac

### ISSUE THREAD

**Issue by MatteoFe** [NateRickard/Plugin.AudioRecorder#6]
I would like to use it but I want to choose the export file type.

I would be glad to try to do it, but I'd like to have a small advice from you: what is the best way to do it?
Maybe add a Mp3Recorder to be switched with the WaveRecorder?

**Comment by NateRickard** [comment]
Yes, that would be the first thing needed.  The audio is recorded in PCM and the wave recorder adds the proper wav riff header, etc.  So an mp3recorder would have to do any compression/encoding/whatever to get the audio data saved into mp3 format.
